/*
 * Runtime tests for brpatch.c's typed predicate dispatch (plan §7).
 *
 * Compiled WITHOUT BINRADAR_EVAL_ONLY so dest()/jnz() are exercised
 * end-to-end, with BRPATCH_CWE119 + BRPATCH_ALLOC_MALLOC so the CWE-119
 * tracker and evaluator are compiled in.  A brpatches.inc is generated by
 * the Python test (tests/test_binradar_setup_cwe119.py) and provided via
 * -I; the descriptor table must stay in sync with the scenarios below.
 *
 * Each scenario prints:
 *   RESULT <name> <br> <jumped>
 * where <br> is the logged branch value and <jumped> is 1 when dest/jnz
 * returned the destination.  The Python test recomputes <br> with the
 * Python mirror (binradar_setup.cwe119_branch_taken) and requires both to
 * agree, so the scenario table below and the Python table must match.
 */

#define TAOSC_DEST 0x1234
#include "../benchmarks/loftix/brpatch.c"

static int failures = 0;

static void set_state(struct STATE *state, const int64_t regs[16],
                      const uint8_t *stack, size_t stack_size)
{
	memset(state, 0, sizeof(*state));
	state->rax = regs[0]; state->rbx = regs[1]; state->rcx = regs[2];
	state->rdx = regs[3]; state->rsi = regs[4]; state->rdi = regs[5];
	state->rsp = (int64_t)(uintptr_t)stack;
	state->rbp = regs[7];
	state->r8 = regs[8]; state->r9 = regs[9]; state->r10 = regs[10];
	state->r11 = regs[11]; state->r12 = regs[12]; state->r13 = regs[13];
	state->r14 = regs[14]; state->r15 = regs[15];
	(void)stack_size;
}

static void set_clamps(const uint64_t clamps[][2], int count)
{
	memset(buffers, 0, sizeof(buffers));
	next = 0;
	for (int i = 0; i < count; i++) {
		buffers[i].begin = clamps[i][0];
		buffers[i].end = clamps[i][1];
	}
	next = (uint8_t)count;
}

/* Run one dest() scenario and print the result. */
static void run_dest(const char *name, uint32_t patch_id,
                     const int64_t regs[16], const uint8_t *stack,
                     const uint64_t clamps[][2], int clamp_count)
{
	struct STATE state;
	uint8_t stack_buf[64] = {0};
	if (stack != NULL)
		memcpy(stack_buf, stack, 64);
	set_state(&state, regs, stack_buf, sizeof(stack_buf));
	set_clamps(clamps, clamp_count);

	int fds[2];
	if (pipe(fds) < 0) {
		printf("RESULT %s pipe-error\n", name);
		failures++;
		return;
	}
	patch_fd = fds[1];
	env_patch_id = patch_id;
	patch_shm = NULL;
	const void *ret = dest(&state);
	close(fds[1]);
	char log[128] = {0};
	ssize_t n = read(fds[0], log, sizeof(log) - 1);
	close(fds[0]);
	if (n <= 0) {
		printf("RESULT %s no-log\n", name);
		failures++;
		return;
	}
	unsigned int id = 0, v = 0;
	int br = -1;
	if (sscanf(log, "[patch] [id %u] [br %d] [v %u]", &id, &br, &v) != 3) {
		printf("RESULT %s bad-log %s\n", name, log);
		failures++;
		return;
	}
	printf("RESULT %s %d %d\n", name, br, ret == (const void *)TAOSC_DEST);
}

/* Run one jnz() scenario and print the result. */
static void run_jnz(const char *name, uint32_t patch_id,
                    uint64_t base, uint64_t index, uint8_t size,
                    uint32_t disp, const uint64_t clamps[][2],
                    int clamp_count)
{
	set_clamps(clamps, clamp_count);
	int fds[2];
	if (pipe(fds) < 0) {
		printf("RESULT %s pipe-error\n", name);
		failures++;
		return;
	}
	patch_fd = fds[1];
	env_patch_id = patch_id;
	patch_shm = NULL;
	const void *ret = jnz(base, index, size, disp, (const void *)TAOSC_DEST);
	close(fds[1]);
	char log[128] = {0};
	ssize_t n = read(fds[0], log, sizeof(log) - 1);
	close(fds[0]);
	if (n <= 0) {
		printf("RESULT %s no-log\n", name);
		failures++;
		return;
	}
	unsigned int id = 0, v = 0;
	int br = -1;
	if (sscanf(log, "[patch] [id %u] [br %d] [v %u]", &id, &br, &v) != 3) {
		printf("RESULT %s bad-log %s\n", name, log);
		failures++;
		return;
	}
	printf("RESULT %s %d %d\n", name, br, ret == (const void *)TAOSC_DEST);
}

int main(void)
{
	/* Shared scenario vectors (keep in sync with the Python test). */
	static const int64_t regs0[16] = {0};
	static const int64_t regs_ptr_inside[16] = {0x1000};
	static const int64_t regs_ptr_outside[16] = {0x3000};
	static const int64_t regs_ptr_boundary[16] = {0x2000};
	static const int64_t regs_ptr_zero[16] = {0};
	static const int64_t regs_size_equal[16] = {0, 0x1000};
	static const int64_t regs_size_inside[16] = {0, 0x800};
	static const int64_t regs_size_scale8[16] = {0, 0x1ff};
	static const int64_t regs_size_overflow[16] = {0, 0x2000000000000000LL};
	static const int64_t regs_multi[16] = {0x2500};
	static const int64_t regs_size_multi_none[16] = {0, 0x5000};

	static const uint8_t stack_ptr64[64] = {0x00, 0x15, 0x00, 0x00,
	                                         0x00, 0x00, 0x00, 0x00};
	static const uint8_t stack_size16[64] = {0x00, 0x05, 0x00, 0x00,
	                                         0x00, 0x00, 0x00, 0x00};
	static const uint8_t stack_size8[64] = {0xff};

	static const uint64_t clamp1[][2] = {{0x1000, 0x2000}};
	static const uint64_t clamp2[][2] = {{0x1000, 0x2000}, {0x2000, 0x3000}};
	static const uint64_t clamp_zero[][2] = {{0, 0}};

	/* dest() scenarios: patch ids refer to the generated brpatches.inc:
	 *   0: "p0" (false)            1: "=p1p1" (generic, always true)
	 *   2: "c1p0"                  3: "c1s64i0"
	 *   4: "c2p1q1"                5: "c2s16i0q2"
	 *   6: "c2p1q8"                7: "c1s32i0" (malformed descriptor)
	 */
	run_dest("ptr-reg-inside", 2, regs_ptr_inside, NULL, clamp1, 1);
	run_dest("ptr-reg-outside", 2, regs_ptr_outside, NULL, clamp1, 1);
	run_dest("ptr-reg-boundary", 2, regs_ptr_boundary, NULL, clamp1, 1);
	run_dest("ptr-stack-inside", 3, regs0, stack_ptr64, clamp1, 1);
	run_dest("ptr-zero-clamp", 2, regs_ptr_zero, NULL, clamp_zero, 1);
	run_dest("size-reg-equal", 4, regs_size_equal, NULL, clamp1, 1);
	run_dest("size-reg-inside", 4, regs_size_inside, NULL, clamp1, 1);
	run_dest("size-reg-scale8", 6, regs_size_scale8, NULL, clamp1, 1);
	run_dest("size-reg-overflow", 6, regs_size_overflow, NULL, clamp1, 1);
	run_dest("size-stack16", 5, regs0, stack_size16, clamp1, 1);
	run_dest("size-stack8", 4, regs0, stack_size8, clamp1, 1);
	run_dest("ptr-multi-clamp", 2, regs_multi, NULL, clamp2, 2);
	run_dest("size-multi-clamp-none", 4, regs_size_multi_none, NULL, clamp2, 2);
	run_dest("malformed-descriptor", 7, regs_ptr_inside, NULL, clamp1, 1);
	run_dest("unknown-id", 99, regs_ptr_inside, NULL, clamp1, 1);
	run_dest("generic-always-true", 1, regs0, NULL, clamp1, 1);
	run_dest("patch-id-0", 0, regs_ptr_inside, NULL, clamp1, 1);

	/* jnz() scenarios: effective address = base + index*size + disp. */
	run_jnz("jnz-id0-inside", 0, 0x1000, 0, 1, 0, clamp1, 1);
	run_jnz("jnz-id1-inside", 1, 0x1000, 0, 1, 0, clamp1, 1);
	run_jnz("jnz-id1-outside", 1, 0x3000, 0, 1, 0, clamp1, 1);
	run_jnz("jnz-id1-indexed", 1, 0x1000, 2, 8, 0x10, clamp1, 1);
	run_jnz("jnz-id1-multi", 1, 0x2500, 0, 1, 0, clamp2, 2);

	/* Dynamic selection: patch_shm {id, v} overrides env_patch_id. */
	{
		static const uint32_t shm[2] = {1, 7};
		set_clamps(clamp1, 1);
		int fds[2];
		pipe(fds);
		patch_fd = fds[1];
		env_patch_id = MAGIC_VALUE_PATCH;
		patch_shm = shm;
		const void *ret = jnz(0x3000, 0, 1, 0, (const void *)TAOSC_DEST);
		close(fds[1]);
		char log[128] = {0};
		ssize_t n = read(fds[0], log, sizeof(log) - 1);
		close(fds[0]);
		unsigned int id = 0, v = 0;
		int br = -1;
		if (n > 0
				&& sscanf(log, "[patch] [id %u] [br %d] [v %u]",
				          &id, &br, &v) == 3)
			printf("RESULT jnz-dynamic %d %d %u %u\n", br,
			       ret == (const void *)TAOSC_DEST, id, v);
		else {
			printf("RESULT jnz-dynamic no-log\n");
			failures++;
		}
	}

	/* Tracker semantics: mark arms the hooks; set_size/set_base record. */
	{
		memset(buffers, 0, sizeof(buffers));
		next = 0;
		trace = 0;
		set_size(0x100, 0);   /* trace == 0: no-op */
		set_base(0x5000);     /* trace == 0: no-op */
		mark(1);              /* trace becomes 1 */
		set_size(0x200, 0);   /* records end = 0x200 */
		set_base(0x6000);     /* records begin = 0x6000, end += 0x6000 */
		if (buffers[0].begin != 0x6000 || buffers[0].end != 0x6200) {
			printf("RESULT tracker-record FAIL %llx %llx\n",
			       (unsigned long long)buffers[0].begin,
			       (unsigned long long)buffers[0].end);
			failures++;
		} else {
			printf("RESULT tracker-record PASS\n");
		}
		/* Ring wrap: next is uint8_t; 255 more records after the
		 * tracker-record scenario (next == 1) wraps it to 0. */
		for (int i = 0; i < 255; i++) {
			trace = 1;
			set_size(0x10, 0);
			set_base(0x1000);
		}
		if (next != 0) {
			printf("RESULT tracker-ring FAIL next=%u\n", (unsigned)next);
			failures++;
		} else {
			printf("RESULT tracker-ring PASS\n");
		}
	}

	if (failures) {
		printf("FAILED %d\n", failures);
		return 1;
	}
	printf("ALL-PASS\n");
	return 0;
}
