import "../../Justfile"
set dotenv-filename := "config.env"
set dotenv-load

default:
    just --list

poc_input := env("POC_INPUT")
binary := env("BINARY")
test_cmd := env("TEST_CMD")
target_function_entry := env("TARGET_FUNCTION_ENTRY")
patch_loc := env("PATCH_LOC")
workdir := justfile_dir()

objdump:
    objdump -d {{binary}}.orig > {{binary}}.orig.asm
    # objdump -d {{binary}}.good > {{binary}}.good.asm
    # objdump -d {{binary}}.bad > {{binary}}.bad.asm

show:
    echo "libafl_dir: {{LIBAFL_PATH}}"
    echo "QEMU_STACKTRACE: {{QEMU_STACKTRACE}}"
    echo "test_cmd: {{test_cmd}}"
    echo {{QEMU_STACKTRACE}}

st:
    cargo run --manifest-path={{QEMU_STACKTRACE}}/Cargo.toml -- -p {{patch_loc}} -i {{poc_input}} ./{{binary}}.orig -- {{test_cmd}}

stgood:
    cargo run --manifest-path={{QEMU_STACKTRACE}}/Cargo.toml -- -p {{patch_loc}} -i {{poc_input}} ./{{binary}}.good -- {{test_cmd}}

stbad:
    cargo run --manifest-path={{QEMU_STACKTRACE}}/Cargo.toml -- -p {{patch_loc}} -i {{poc_input}} ./{{binary}}.bad -- {{test_cmd}}

fuzzolic:
    uv run {{FUZZOLIC_SCRIPT}} {{FUZZOLIC_BASE_ARGS}} --forkserver-entrypoint {{target_function_entry}} -i {{poc_input}} -o workdir -- ./{{binary}}.orig {{test_cmd}}

binradar:
    uv run {{BINRADAR_SCRIPT}} -w {{workdir}} -i {{poc_input}} -o {{workdir}}/out