FROM ubuntu:22.04

RUN sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list && cat /etc/apt/sources.list

# dependencies
RUN apt update -y && \
	DEBIAN_FRONTEND=noninteractive apt-get build-dep -y qemu-user && DEBIAN_FRONTEND=noninteractive apt install -y lsb-release wget software-properties-common gnupg

RUN wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 18 && \
	update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 50 && \
	update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-18 50 && \
	update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 50 && \
	update-alternatives --install /usr/bin/llvm-as llvm-as /usr/bin/llvm-as-18 50 && \
	update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-18 50 && \
	update-alternatives --install /usr/bin/llvm-dis llvm-dis /usr/bin/llvm-dis-18 50 && \
	update-alternatives --install /usr/bin/llvm-link llvm-link /usr/bin/llvm-link-18 50 && \
	update-alternatives --install /usr/bin/lld lld /usr/bin/lld-18 50
	
RUN DEBIAN_FRONTEND=noninteractive apt install -y \
	emacs curl \
	qemu-user libglib2.0-dev libfdt-dev \
	libpixman-1-dev zlib1g-dev libcapstone-dev \
	strace libprotobuf-dev \
	libibverbs-dev libjpeg62-dev \
	libpng16-16 libjbig-dev \
	build-essential libtool-bin \
	automake flex bison libglib2.0-dev \
	libpixman-1-dev \
	g++ g++-multilib \
	gcc libc6 libstdc++6 \
	linux-libc-dev gcc-multilib \
	apt-transport-https libtool libtool-bin autoconf \
    git gdb dumb-init valgrind ninja-build \
	time xxd openssh-server && \
	apt clean

WORKDIR /root/prog
RUN git clone https://github.com/git/git.git && cd git && git checkout v2.54.0 && make configure && ./configure && make -j 32 && make install

# Install mise
ENV MISE_DATA_DIR=/mise
ENV MISE_CONFIG_DIR=/mise
ENV MISE_GLOBAL_CONFIG_FILE=/mise/config.toml
ENV MISE_CACHE_DIR=/mise/cache
ENV MISE_INSTALL_PATH=/usr/local/bin/mise
ENV PATH=/mise/shims:/usr/local/bin:$PATH

RUN curl https://mise.run | sh
RUN mise use -g python@3.10 uv@0.11 rust@1.95 zig@0.15 cmake@3.31 just

# Cache deps for fuzzolic
WORKDIR /root/fuzzolic
COPY pyproject.toml uv.lock ./

RUN uv venv && uv sync

ENV VIRTUAL_ENV=/root/fuzzolic/.venv

# fuzzolic
COPY . .

# Build QEMU tracer
RUN cd tracer && mkdir build && cd build && ../configure --target-list=x86_64-linux-user && make -j 32 

# Build custom Z3
RUN cd solver && mkdir build && cd build && cmake .. && make -j 32

# Build LibAFL
RUN cd /root/fuzzolic/LibAFL/fuzzers/binary_only/qemu_stacktrace && cargo build --release
RUN cd /root/fuzzolic/LibAFL/fuzzers/binary_only/qemu_targeted_simple && cargo build --release

# Build AFL++
RUN cd utils && git clone https://github.com/AFLplusplus/AFLplusplus.git && \
	cd AFLplusplus && git checkout 2dac4e7 && \
	git apply ../afl-showmap.c.patch && \
	make -j `nproc` all 
RUN cd utils/AFLplusplus/qemu_mode && uvx virtualenv venv && source venv/bin/activate && \
    pip install "meson==0.56.2" && ./build_qemu_support.sh
ENV AFL_PATH=/root/fuzzolic/utils/AFLplusplus
RUN echo "export AFL_PATH=/root/fuzzolic/utils/AFLplusplus" >> $BASH_ENV

# Build fuzzolic tests
RUN cd tests && make

CMD bash
