FROM ubuntu:22.04

RUN sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list && cat /etc/apt/sources.list

# dependencies
RUN apt update -y && \
	DEBIAN_FRONTEND=noninteractive apt-get build-dep -y qemu-user && DEBIAN_FRONTEND=noninteractive apt install -y lsb-release wget software-properties-common gnupg

RUN wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 18 && \
	update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 50 && \
	update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-18 50 && \
	update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 50 && \
	update-alternatives --install /usr/bin/llvm-as llvm-as /usr/bin/llvm-as-18 50 && \
	update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-18 50 && \
	update-alternatives --install /usr/bin/llvm-dis llvm-dis /usr/bin/llvm-dis-18 50 && \
	update-alternatives --install /usr/bin/llvm-link llvm-link /usr/bin/llvm-link-18 50 && \
	update-alternatives --install /usr/bin/lld lld /usr/bin/lld-18 50
	
RUN DEBIAN_FRONTEND=noninteractive apt install -y \
	emacs curl \
	qemu-user libglib2.0-dev libfdt-dev \
	libpixman-1-dev zlib1g-dev libcapstone-dev \
	strace cmake python3 python3-pip python3-tomli python3-venv libprotobuf-dev \
	libibverbs-dev libjpeg62-dev \
	libpng16-16 libjbig-dev \
	build-essential libtool-bin python3-dev \
	automake flex bison libglib2.0-dev \
	libpixman-1-dev \
	python3-setuptools wget \
	g++ g++-multilib \
	gcc cmake libc6 libstdc++6 \
	linux-libc-dev gcc-multilib \
	apt-transport-https libtool libtool-bin autoconf \
    git gdb dumb-init valgrind ninja-build \
	time xxd openssh-server bear && \
	apt clean && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /root/prog
RUN git clone https://github.com/git/git.git && cd git && git checkout v2.54.0 && make configure && ./configure && make -j 32 && make install
RUN git clone https://github.com/Kitware/CMake.git && cd CMake && git checkout v3.31.12 && ./bootstrap && make -j 32 && make install

# Install uv and rustup
ARG UID=1000
ARG GID=1000
RUN groupadd -g ${GID} binradar && useradd -m -u ${UID} -g binradar -s /bin/bash binradar
RUN chown -R binradar:binradar /root/prog
RUN mkdir -p /workspace && chown -R binradar:binradar /workspace
USER binradar
ENV HOME=/home/binradar
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/home/binradar/.local/bin:/home/binradar/.cargo/bin:$PATH"
RUN cargo install just

# Cache deps for fuzzolic
WORKDIR /workspace/fuzzolic
COPY --chown=binradar:binradar pyproject.toml uv.lock ./

RUN uv venv && uv sync

# fuzzolic
COPY --chown=binradar:binradar . .

# Build QEMU tracer
RUN cd tracer && mkdir build && cd build && ../configure --target-list=x86_64-linux-user && bear -- make -j 32 

# Build custom Z3
RUN cd solver && mkdir build && cd build && cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. && make -j 32

# Build LibAFL

# qemu_stacktrace: build.rs auto-builds libafl_qemu_asan_guest.so into its target dir
# RUN cargo build --release --manifest-path=/workspace/fuzzolic/LibAFL/fuzzers/binary_only/qemu_stacktrace/Cargo.toml
# qemu_targeted_simple: reuse the same DSO
# RUN mkdir -p /workspace/fuzzolic/LibAFL/fuzzers/binary_only/qemu_targeted_simple/target/release && \
#     cp /workspace/fuzzolic/LibAFL/fuzzers/binary_only/qemu_stacktrace/target/release/libafl_qemu_asan_guest.so /workspace/fuzzolic/LibAFL/fuzzers/binary_only/qemu_targeted_simple/target/release/
# RUN cargo build --release --manifest-path=/workspace/fuzzolic/LibAFL/fuzzers/binary_only/qemu_targeted_simple/Cargo.toml

# Build AFL++
# AFLplusplus: just old version for now, apply afl-showmap.c.patch
# RUN cd utils && rm -rf AFLplusplus && git clone -b targeted https://github.com/hsh814/AFLplusplus.git AFLplusplus
RUN cd utils/AFLplusplus && git switch targeted && make -j `nproc` all && \ 
    cd qemu_mode && uvx virtualenv venv && . venv/bin/activate && \
    pip install "meson==0.56.2" && ./build_qemu_support.sh
# RUN cd utils && rm -rf binradar-aflplusplus && git clone -b binradar https://github.com/hsh814/AFLplusplus.git binradar-aflplusplus
# cp ../../binradar-trace.c qemuafl/linux-user/binradar-trace.c && cp ../../binradar-trace.h qemuafl/qemuafl/binradar-trace.h && git apply ../../qemuafl.patch
RUN cd utils/binradar-aflplusplus && git switch binradar && make -j `nproc` all && \
    cd qemu_mode && uvx virtualenv venv && . venv/bin/activate && \
	pip install "meson==0.56.2" && ./build_qemu_support.sh
ENV AFL_PATH=/workspace/fuzzolic/utils/AFLplusplus

# Build fuzzolic tests
RUN cd tests && make

CMD bash
